--- 
title: "Inferência =)"
author: "Thalis Rebouças"
date: "`r paste('Última atualização:', format(Sys.Date(), '%d/%m/%Y'))`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
url: "https://thalisreboucas.github.io/my_theme/"
github-repo: thalisreboucas/my_theme
favicon: "favicon.png"
description: "Livro de Inferência."
---

# Introdução {#intro}

```{r eval=FALSE, include=FALSE}


bookdown::render_book(output_dir = "E:/edime/Thalis/CadernoR/my_theme/docs")

```
  
Esse será um Livro para ajudar na cadeira de inferência !!!


As duas principais definições básicas em Inferência Estatística são as de população e amostra. Esses são os dois conceitos que são repetidos inúmeras vezes nesse material e que são explanados a seguir.

## Definições 

Seja _X_ uma variável aleatória (v.a.) com função de densidade (ou de
probabilidade) $f (x|\theta)$, em que $\theta$ é um parâmetro desconhecido. Chamamos
de inferência estatística o problema que consiste em especificar um ou
mais valores para $\theta$, baseado em um conjunto de valores observados de X.

>
>**População**
>
> O conjunto de valores de uma característica (observável) associada auma coleção de indivíduos ou objetos de interesse é dito ser uma população.
>

>
> **Amostra**
>
>É um conjunto de dados coletados e/ou selecionados de uma populaçãopor um procedimento definido. Os elementos de uma amostra são conhecidos como pontos amostrais,unidades amostrais ou observações.É qualquer subconjunto da população.
>

É, portanto, a partir da amostra $X_1,X_2,...,X_n$ que conseguimos obter informação sobre o parâmetro $\theta$ de interesse. Mas como ainda não sabemos o que é um parâmetro, vamos explicar na próxima seção.


>
> **Estatísticas**
>
> Uma estatística é uma característica da amostra, ou seja, uma estatística
_T_ é uma função de $X_1,X_2,...,X_n$ , não depende de parâmetros desconhecidos
>
> A média, a mediana, o mínimo e o máximo, por exemplo, são exemplos de estatísticas!!!
>


>
> **Parâmetro**
>
> Um parâmetro é uma medida usada para descrever uma característica da
população.Em geral são desconhecidos e têm-se o objetivo de estimá-los.
>
>Considere uma população identificada pela v.a X, seriam parâmetros a
média E(X) e sua variância Var(X)
>
> **Espaço Parâmetro**   
 >Seja $X_1,X_2,...,X_n$ uma amostra aleatória de uma variávelaleatória com distribuição $f(X_i;\theta)$, em que $\theta$ é o parâmetro associado à distribuição. O intervalo $\Theta$ de valores possíveis para $\theta$ é chamado espaço paramétrico.
>

>
> **Estimador**
>
>Um estimador é uma estatística cujas realizações são utilizadas para obter estimações dos parâmetros de um modelo probabilístico e uma realização ou um valor particular se conhece como estimação.
>
>A estatística que assuma qualquer valor em $\Theta$ é uma estimador para $\theta$.
>




## Amostra Aleatória Simples

Seja _X_ uma variável aleatória com distribuição de probabilidade ou função densidade de probabilidade $f (x|\theta)$. Sejam $X_1,X_2,...,X_n$ variáveis aleató-rias independentes e identicamente distribuídas, indicandonretiradas de uma população _P_.  Então, $X_1,X_2,...,X_n$ é uma amostra aleatória simples de _P_.

Perceba que quando coletamos as observações por meio da amostra aleatória simples, podemos afirmar que temos uma amostra de variáveis aleatórias independentes (a retirada de uma observação não tem relação com a retirada de nenhuma outra) e identicamente distribuídas (cada observação tem a mesma distribuição deprobabildiade ou função densidade de probabilidade). A partir dessas duas características, podemos encontrara distribuição conjunta dessa amostra, que é apresentada formalmente a seguir.

### Distribuição da amostral

Seja $X_1,X_2,...,X_n$ numa amostra aleatória de umavariável aleatória com distribuição $f (x_i|\theta)$. A distribuição da respectiva amostra é a distribuição conjuntade $X_1,X_2,...,X_n$ dada por:
\[f_{(X_1,X_2,...,X_n)} = f_{X_1}(x_1;\theta) f_{X_2}(x_2;\theta) \ldots f_{X_3}(x_3;\theta)
\]
\[ = \prod_{k=1}^{n} f_{X_k}(x_k;\theta) \]

> A essa distribuição conjunta dá-se o nome de **função de verossimilhança.**

## Estatísticas particularidades

### Estatística suficiente

Dentre todas as estatísticas, nesta subseção vamos estudar aquela que a literatura chama de estatística suficiente, cuja quantidade permite um resumo das informações trazidas pela amostra, sendo capaz de resumiros dados sem perder nenhuma informação sobre $\theta$ .

>
>**Definição:**
>
>Seja $X_1,X_2,...,X_n$ uma amostra aleatória de uma população com função de probabilidade ou função densidade de probabilidade $f(X|\theta)$, com $\theta \in \Theta$.  A estatística $T=T(X_1,X_2,...,X_n)$ é dita ser suficiente para $\theta$ se, e somente se, a distribuição conjuntade $(X_1,X_2,...,X_n)$ dado T=t não depende de $\theta$.
>

Podemos afirmar, nesse sentido, que, conhecida uma estatística suficiente, os dados da amostra passama ser desconsiderados ou irrelevantes, dado que não há mais informações adicionais a serem retiradas sobre oparâmetro de interesse, embora ainda possa conter informações relevantes sobre o modelo estatístico.

